### PR TITLE
Targeting issue-18 - removing clock buttons, click on clocks instead.

### PR DESCRIPTION
**Pull request by shaahin**
* got rid of clock buttons.
* Added `UITapGestureRecognizer`s to clocks theirselves.
* Instead of disabling and enabling,

### CODE REVIEW

**Comment by joanb** [comment]
I will revise this later today! thank you 😄

**Review by joanb — APPROVED** [review]
thank you for your contribution! Looks awesome. Maybe when it's paused it would be nice to see which player's clock is active, because only one of the two is clickable but both are disabled :)
That can come in another PR. thank you 💪

**Comment by joanb** [comment]
@all-contributorsbot please add @shaahin for code

**Comment by shaahin** [comment]
Thanks @joanb :D Very glad to help.
Oh, yes. I will send that in a separate PR though 🍀😀

**Comment by joanb** [comment]
Cool!! thank you @shaahin! here's already an issue created here -> #31  🚀 😄

**Pull request merged**
