### PR TITLE
UI hidding when pause button was pressed

### PR DESCRIPTION
**Pull request by KarasIlia**
Hello, this is my first PR. I hope I understood the issue correctly.

### CODE REVIEW

**Comment by joanb** [comment]
Hey there! Thank you a lot for this Pull request!
I'll check it as soon as posible. In the mean time, let me add you to the contributors page for code :)

**Comment by joanb** [comment]
@all-contributors please add @KarasIlia  for code

**Comment by joanb** [comment]
Hey there! @KarasIlia 
I've been checking the code and the proposed behavior, and I really love the reset animation :)
There's one thing that i consider important: Right after clicking on pause, there's no option to resume the timers, it only allows to reset the game.
Could you make the resume button visible? 
Thanks in advance, and keep up with the awesome work! 🚀

**Comment by KarasIlia** [comment]
> Could you make the resume button visible?

How can i see the resume button not yet implemented? i'll try to do it tomorrow.

**Comment by joanb** [comment]
Yes sorry, that's a new button that needs to be added. 
The idea of the issue was to initially hide the reset button and only show it when the pause button is clicked (when the game is on pause state). 
When paused, it would be nice to see the clocks so players can see their remaining times, but also give the option to Reset and Resume the game. I edited the issue #5 to give a more detailed description.
Sorry about the confusion, I will provide more detailed issues from now on. 
Thank you a lot for your collaboration 💪

**Comment by KarasIlia** [comment]
Oh, I get it. I’ll do a new commit!)

**Comment by KarasIlia** [comment]
I thought it’s better to just disable the buttons than to hide completely. I also solved the constraints issues.

**Comment by joanb** [comment]
Hey there! I like the button disable approach. 
However i've seen that the buttons are not displaying the full text (tested on iPhone6). It shows `...` for the pause button and `R...e` for the resume Button.
There are a few more fixes to deal with, but when let's merge the code when he text is fixed. I'll make other issues for the fixes.
As always, thank you very much for your huge effort, keep up with the good work :)

**Comment by KarasIlia** [comment]
Now the text should display well.

**Comment by joanb** [comment]
It's shown perfectly now :) thanks for your collaboration 🎉 
Don't hesitate to keep contributing :) Let's try to release this app 💪

**Pull request merged**
