### PR TITLE
[Fixed]Don't disable both clocks when paused

### PR DESCRIPTION
**Pull request by jpauljm**

### CODE REVIEW

**Comment by joanb** [comment]
Thank you a lot for your contribution!! 😄

**Comment by joanb** [comment]
@all-contributorsbot please add @aKANJx for code

**Comment by jpauljm** [comment]
I’m honored! Thanks!
Can I create a new branch with the app using SwiftUI+Combine?

**Comment by joanb** [comment]
That would be awesome! 
I haven't tried It yet. It would be great contribution, but I can not assure you those technologies will be the ones used at least in the MVP version of this project. Is that ok to you?
Let's give it a try!
Also, thank you for your participation! I'm also honored :)

**Comment by jpauljm** [comment]
Yeah It’s fine for me!

(aKANJ)
Senior iOS and Unity Engineer | UnityBR Leader
@aKANJx

**Pull request merged**
